#!/bin/bash

# ASCII Art Banner
echo '
  ______                     ______      __         __  __           __  _            
 /_  __/__  ______________ _/ ____/_  __/ /_  ___  / / / /___  _____/ /_(_)___  ____ _
  / / / _ \/ ___/ ___/ __ `/ /   / / / / __ \/ _ \/ /_/ / __ \/ ___/ __/ / __ \/ __ `/
 / / /  __/ /  / /  / /_/ / /___/ /_/ / /_/ /  __/ __  / /_/ (__  ) /_/ / / / / /_/ / 
/_/  \___/_/  /_/   \__,_/\____/\__,_/_.___/\___/_/ /_/\____/____/\__/_/_/ /_/\__, /  
                                                                             /____/   
'

# CPU Usage
cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')

# RAM Usage
ram_usage=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')

# Disk Usage
disk_usage=$(df -h / | awk '$NF=="/"{printf "%s", $5}')

# IPv4 Address
ipv4_address=$(hostname -I | awk '{print $1}')

echo "CPU Usage: $cpu_usage"
echo "RAM Usage: $ram_usage"
echo "Disk Usage: $disk_usage"
echo "IPv4 Address: $ipv4_address"
